/**
 * Step output -> step input. The thing that makes `dependsOn` an edge that
 * carries data rather than an edge that only carries timing.
 *
 * Before this, `Scheduler.execute()` discarded `outcome.output` entirely and
 * every step's input was frozen at plan time. Two places worked anyway by
 * hardcoding the value the previous step was going to produce — including the
 * walking skeleton, the demo whose job is proving the pipe works end to end.
 * Delete `dependsOn` from either and nothing changed.
 *
 * THE SYNTAX IS DELIBERATELY POOR:
 *
 *   { "$from": "<stepId>.<outputField>" }
 *
 * One dot. One declared output field. No paths into the value, no array
 * indexing, no transforms, no expression language, no fallbacks. Everything it
 * cannot express is written down as a limit rather than discovered later as a
 * gap — see the PR body for the current list. A plan language grows one
 * convenience at a time until it is a programming language nobody designed,
 * and this one has to be validated by a machine and generated by a model.
 *
 * WHY THERE IS NO TYPE PREDICATE HERE. The obvious shape for this file is
 * `function isReference(v: unknown): v is StepReference`, and that is precisely
 * the construct #66 found drifted in `looksLikeCapability` and #65 found
 * drifted in `isValidMessages`: TypeScript never verifies a predicate's body
 * against the type it asserts. So the job is split in two and neither half is
 * an assertion:
 *
 *   · `holdsReferenceKey` answers "was this INTENDED as a reference" — the
 *     presence of the `$from` key, nothing more. A boolean, not a narrowing.
 *   · `parseReference` answers "is it well-formed", and THROWS with the reason
 *     if not.
 *
 * The consequence is the important part: a malformed reference can never be
 * silently passed through as a literal object. `{ "$from": "fetch" }` is a
 * missing dot, not a value.
 */

import type { Broker } from "./broker";
import type { MissionSpec } from "./types";

/** The one key. Exported so a test cannot drift from the implementation. */
export const REFERENCE_KEY = "$from";

export class PlanReferenceError extends Error {}

/** A parsed reference. Produced only by `parseReference`, never asserted. */
export interface ParsedReference {
  stepId: string;
  field: string;
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * Was this value INTENDED as a reference? The presence of the key decides, and
 * that is the whole point: an object carrying `$from` in any form is a
 * reference someone meant to write, so a malformed one is an error rather than
 * a literal that quietly reaches the capability.
 */
export function holdsReferenceKey(value: unknown): boolean {
  return isPlainObject(value) && Object.prototype.hasOwnProperty.call(value, REFERENCE_KEY);
}

/**
 * Parse, or throw saying exactly what is wrong. `at` is the input path, so the
 * message names the field the author has to fix.
 */
export function parseReference(value: unknown, at: string): ParsedReference {
  if (!isPlainObject(value)) {
    throw new PlanReferenceError(`${at}: a reference must be an object`);
  }
  const keys = Object.keys(value);
  if (keys.length !== 1) {
    // A sibling key means the author expected the reference to be merged into
    // something, which this syntax does not do. Refusing beats resolving the
    // reference and silently dropping the rest.
    throw new PlanReferenceError(
      `${at}: a reference carries "${REFERENCE_KEY}" and nothing else, got ${JSON.stringify(keys)}`,
    );
  }
  const raw = (value as Record<string, unknown>)[REFERENCE_KEY];
  if (typeof raw !== "string") {
    throw new PlanReferenceError(`${at}: "${REFERENCE_KEY}" must be a string, got ${typeof raw}`);
  }

  const parts = raw.split(".");
  if (parts.length !== 2 || parts[0] === "" || parts[1] === "") {
    throw new PlanReferenceError(
      `${at}: "${raw}" is not "<stepId>.<outputField>" — exactly one dot, both sides non-empty. ` +
        `This syntax has no paths into a value, no array indexing and no transforms`,
    );
  }
  return { stepId: parts[0], field: parts[1] };
}

/**
 * Every reference in an input, with the path it sits at.
 *
 * References may appear ANYWHERE in the input tree, not only at the top level.
 * That is a decision, and the case that forced it is real: `llm.chat` takes
 * `messages: [{ role, content, trust }]`, so piping a previous step's output
 * into a message is a nested position or it is nothing.
 *
 * "No nesting" in the syntax rule is about the REFERENCE — `fetch.a.b` is
 * still refused. Where the reference may sit is a different question.
 *
 * `maxDepth` mirrors `inputContract.ts`'s cap: the plan is trusted, but it is
 * about to be generated by a model, and a walk with no bound is a stack
 * overflow waiting for its first cyclic input.
 */
export function referencesIn(
  input: unknown,
  at = "input",
  depth = 0,
  found: Array<{ at: string; ref: ParsedReference }> = [],
): Array<{ at: string; ref: ParsedReference }> {
  if (depth > 12) throw new PlanReferenceError(`${at}: input nests deeper than 12`);
  if (holdsReferenceKey(input)) {
    found.push({ at, ref: parseReference(input, at) });
    return found;
  }
  if (Array.isArray(input)) {
    input.forEach((item, i) => referencesIn(item, `${at}[${i}]`, depth + 1, found));
  } else if (isPlainObject(input)) {
    for (const key of Object.keys(input)) {
      referencesIn(input[key], `${at}.${key}`, depth + 1, found);
    }
  }
  return found;
}

/**
 * PLAN TIME. Every reference in the mission is checked before any step runs.
 *
 * The fifth check is the one #66 exists for: a reference naming a field the
 * producing capability does not declare is refused HERE. Before `outputs`
 * existed this was unachievable, and the reference would have resolved to
 * `undefined` several steps into a running mission.
 *
 * The fourth is the structural kill of facade #2: a reference to a step this
 * one does not depend on is not a data flow, it is a race.
 */
export function validateReferences(spec: MissionSpec, broker: Broker): void {
  const byId = new Map(spec.steps.map((s) => [s.id, s]));

  for (const step of spec.steps) {
    for (const { at, ref } of referencesIn(step.input, `${step.id}.input`)) {
      const producer = byId.get(ref.stepId);
      if (!producer) {
        throw new PlanReferenceError(`${at}: no step "${ref.stepId}" in this mission`);
      }
      if (ref.stepId === step.id) {
        throw new PlanReferenceError(`${at}: a step cannot reference its own output`);
      }
      if (!step.dependsOn.includes(ref.stepId)) {
        throw new PlanReferenceError(
          `${at}: references "${ref.stepId}" but does not depend on it. Add it to dependsOn — ` +
            `without the edge the scheduler may run both at once and the value would be a race`,
        );
      }

      const outputs = broker.manifest(producer.capabilityId).outputs;
      if (!Object.prototype.hasOwnProperty.call(outputs, ref.field)) {
        const declared = Object.keys(outputs);
        throw new PlanReferenceError(
          `${at}: "${producer.capabilityId}" declares no output "${ref.field}". ` +
            (declared.length ? `It returns: ${declared.join(", ")}.` : "It returns nothing."),
        );
      }
    }
  }
}

/**
 * RUN TIME. Replace every reference with the value it names.
 *
 * `readOutput` is supplied by the caller rather than an artifact store being
 * imported here, because WHERE a previous step's output lives is the
 * scheduler's knowledge (the event log) and this module's job is the shape.
 * The scheduler's implementation goes log -> `evidence.outputArtifactId` ->
 * store, so resolution survives a resume; a map of values held in the
 * scheduler would not, and "reproducible" would be a facade the day it shipped.
 *
 * Returns the input unchanged, by identity, when it holds no references — so a
 * caller can tell whether anything was resolved without comparing structures.
 */
export async function resolveInput(
  input: unknown,
  readOutput: (stepId: string) => Promise<unknown>,
  at = "input",
  depth = 0,
): Promise<unknown> {
  if (depth > 12) throw new PlanReferenceError(`${at}: input nests deeper than 12`);

  if (holdsReferenceKey(input)) {
    const ref = parseReference(input, at);
    const output = await readOutput(ref.stepId);
    if (!isPlainObject(output)) {
      throw new PlanReferenceError(
        `${at}: step "${ref.stepId}" produced no readable output to reference`,
      );
    }
    if (!Object.prototype.hasOwnProperty.call(output, ref.field)) {
      // Plan validation already proved the capability DECLARES this field.
      // Reaching here means the declaration and the run disagree, which the
      // output contract should have caught — so say that, rather than handing
      // back `undefined` and letting it surface as a confusing refusal one
      // layer down.
      throw new PlanReferenceError(
        `${at}: step "${ref.stepId}" ran but its output has no "${ref.field}". Its manifest ` +
          `declares one, so the manifest and the implementation disagree`,
      );
    }
    return output[ref.field];
  }

  if (Array.isArray(input)) {
    const items = await Promise.all(
      input.map((item, i) => resolveInput(item, readOutput, `${at}[${i}]`, depth + 1)),
    );
    return items.every((v, i) => v === input[i]) ? input : items;
  }

  if (isPlainObject(input)) {
    const out: Record<string, unknown> = {};
    let changed = false;
    for (const key of Object.keys(input)) {
      const value = await resolveInput(input[key], readOutput, `${at}.${key}`, depth + 1);
      if (value !== input[key]) changed = true;
      out[key] = value;
    }
    return changed ? out : input;
  }

  return input;
}
