/**
 * PORT of Scrapling's adaptive element relocation — the "survives a site
 * redesign" super-ability (CLAUDE.md, browser & collection table).
 *
 * Ported from Scrapling 0.4.9 (scrapling/parser.py `Selector.relocate`,
 * `Selector.__calculate_similarity_score`, `Selector.__calculate_dict_diff`,
 * scrapling/core/utils/_utils.py `_StorageTools.element_to_dict`) — logic
 * translated line-for-line, not reimplemented from a description of intent.
 *
 * Fidelity is proven, not asserted: kernel/fixtures/scrapling-golden.json is
 * generated by kernel/fixtures/generate_golden.py, which imports the REAL
 * upstream `Selector` class and calls its private scoring method directly
 * (bypassing the heavy constructor via `object.__new__`) — so the expected
 * scores in that fixture came from Scrapling's own code, not from this port.
 * tests/kernel/scrapling.test.ts asserts this port reproduces every one.
 *
 * Known gap, stated rather than hidden: lxml.html.fromstring's fragment vs.
 * full-document detection is more elaborate than the one heuristic here
 * (`parseFragmentLikeLxml`). That heuristic is proven correct only for the
 * shapes the golden fixtures cover (a bare fragment, and an explicit
 * `<html><body>…`). A capability manifest for this port must not claim
 * fidelity beyond what the golden suite actually exercises.
 */

import { parseDocument } from "htmlparser2";
import type { AnyNode, Element } from "domhandler";
import { sequenceRatio, stringRatio } from "./sequence-matcher";

export interface ElementFingerprint {
  tag: string;
  attributes: Record<string, string>;
  text: string | null;
  path: readonly string[];
  parentName?: string;
  parentAttribs?: Record<string, string>;
  parentText?: string | null;
  siblings?: readonly string[];
  children?: readonly string[];
}

/* ── DOM helpers over htmlparser2/domhandler, mirroring lxml's element model ── */

function isElement(node: AnyNode | null | undefined): node is Element {
  return !!node && node.type === "tag";
}

function isTextNode(node: AnyNode): node is AnyNode & { data: string } {
  return node.type === "text";
}

/** Direct element children, in document order — lxml's `iterchildren()` excluding comments. */
function elementChildren(el: Element): Element[] {
  return el.children.filter(isElement);
}

/**
 * lxml's `element.text`: the text immediately after the opening tag, up to
 * the first CHILD ELEMENT — never descendant text, never a sibling's text.
 *
 * A comment in that leading position stops the run here, same as any other
 * non-text node. Untested against real lxml (none of the golden fixtures put
 * a comment before an element's first real child) — deliberately the
 * conservative choice rather than an unverified "comments don't count" rule.
 */
function leadingText(el: Element): string | null {
  let text = "";
  for (const child of el.children) {
    if (!isTextNode(child)) break; // first non-text child — stop, matching lxml's single .text slot
    text += child.data;
  }
  const trimmed = text.trim();
  return trimmed.length > 0 ? trimmed : null;
}

/** Root-to-element chain of tag names — lxml's `_get_element_path`. */
function pathFromRoot(el: Element): string[] {
  const path: string[] = [];
  let node: Element | null = el;
  while (node) {
    path.unshift(node.name);
    node = isElement(node.parent) ? node.parent : null;
  }
  return path;
}

/** PORT of `_StorageTools.element_to_dict`. */
export function elementToDict(el: Element): ElementFingerprint {
  const result: ElementFingerprint = {
    tag: el.name,
    attributes: { ...el.attribs },
    text: leadingText(el),
    path: pathFromRoot(el),
  };

  const parent = isElement(el.parent) ? el.parent : null;
  if (parent) {
    result.parentName = parent.name;
    result.parentAttribs = { ...parent.attribs };
    result.parentText = leadingText(parent);

    const siblings = elementChildren(parent)
      .filter((sibling) => sibling !== el)
      .map((sibling) => sibling.name);
    if (siblings.length > 0) result.siblings = siblings;
  }

  const children = elementChildren(el).map((child) => child.name);
  if (children.length > 0) result.children = children;

  return result;
}

/** PORT of `Selector.__calculate_dict_diff` — dict key/value similarity, 50/50 weighted. */
function dictDiff(a: Record<string, string>, b: Record<string, string>): number {
  const score =
    sequenceRatio(Object.keys(a), Object.keys(b)) * 0.5 +
    sequenceRatio(Object.values(a), Object.values(b)) * 0.5;
  return score;
}

const STRUCTURAL_ATTRS = ["class", "id", "href", "src"] as const;

/**
 * PORT of `Selector.__calculate_similarity_score`. Same accumulation order
 * as upstream, so a change there is easy to diff against a change here.
 */
export function calculateSimilarityScore(
  original: ElementFingerprint,
  candidate: Element,
): number {
  let score = 0;
  let checks = 0;
  const data = elementToDict(candidate);

  score += original.tag === data.tag ? 1 : 0;
  checks += 1;

  if (original.text) {
    score += stringRatio(original.text, data.text ?? "");
    checks += 1;
  }

  score += dictDiff(original.attributes, data.attributes);
  checks += 1;

  for (const attrib of STRUCTURAL_ATTRS) {
    const originalValue = original.attributes[attrib];
    if (originalValue) {
      score += stringRatio(originalValue, data.attributes[attrib] ?? "");
      checks += 1;
    }
  }

  score += sequenceRatio(original.path, data.path);
  checks += 1;

  if (original.parentName) {
    if (data.parentName) {
      score += stringRatio(original.parentName, data.parentName ?? "");
      checks += 1;

      score += dictDiff(original.parentAttribs ?? {}, data.parentAttribs ?? {});
      checks += 1;

      if (original.parentText) {
        score += stringRatio(original.parentText, data.parentText ?? "");
        checks += 1;
      }
    }
  }

  if (original.siblings && original.siblings.length > 0) {
    score += sequenceRatio(original.siblings, data.siblings ?? []);
    checks += 1;
  }

  return Math.round((score / checks) * 100 * 100) / 100; // round(x, 2), see file docstring
}

/**
 * Parses HTML the way `lxml.html.fromstring` does for the shapes this port
 * has golden proof for: a document already containing `<html>` is parsed
 * as-is; a bare fragment is wrapped in `<html><body>…</body></html>` first.
 * This is a narrower heuristic than lxml's real fragment detection — see the
 * file docstring.
 */
export function parseFragmentLikeLxml(html: string): Element {
  const looksLikeDocument = /<html[\s>]/i.test(html);
  const source = looksLikeDocument ? html : `<html><body>${html}</body></html>`;
  const doc = parseDocument(source, { lowerCaseTags: true, lowerCaseAttributeNames: true });
  const root = doc.children.find(isElement);
  if (!root) throw new Error("scrapling.parseFragmentLikeLxml: no root element parsed");
  return root;
}

/** All descendant elements of `root`, in document order — `.//*`. */
export function allDescendantElements(root: Element): Element[] {
  const out: Element[] = [];
  const walk = (el: Element): void => {
    for (const child of elementChildren(el)) {
      out.push(child);
      walk(child);
    }
  };
  walk(root);
  return out;
}

export interface RelocateResult {
  matches: Element[];
  score: number;
}

/**
 * PORT of `Selector.relocate`. Scans every element in `pageHtml`, scores each
 * against `fingerprint`, and returns every element tied at the highest score
 * — never just the first — provided that score clears `percentage` (upstream
 * default: 40).
 */
/**
 * The best-scoring candidate on the page, WITHOUT applying a threshold.
 *
 * New surface, not a change to the port: `relocate` below still returns
 * `undefined` under its threshold, exactly as upstream does, and the golden
 * fixtures still prove that. This exists because the threshold discards the
 * one number a caller needs to react — how close it actually got. A capability
 * reporting `score: 0` for "nothing cleared 80" is reporting a sentinel as if
 * it were a measurement.
 */
export function bestMatch(
  fingerprint: ElementFingerprint,
  pageHtml: string,
): RelocateResult | undefined {
  const root = parseFragmentLikeLxml(pageHtml);
  const scoreTable = new Map<number, Element[]>();

  for (const node of allDescendantElements(root)) {
    const score = calculateSimilarityScore(fingerprint, node);
    const bucket = scoreTable.get(score);
    if (bucket) bucket.push(node);
    else scoreTable.set(score, [node]);
  }

  if (scoreTable.size === 0) return undefined;

  const highest = Math.max(...scoreTable.keys());
  return { matches: scoreTable.get(highest)!, score: highest };
}

export function relocate(
  fingerprint: ElementFingerprint,
  pageHtml: string,
  percentage = 40,
): RelocateResult | undefined {
  const best = bestMatch(fingerprint, pageHtml);
  if (!best || best.score < percentage) return undefined;
  return best;
}

/** Convenience: fingerprint the first matching descendant element (or root) of a page. */
export function fingerprintFirst(pageHtml: string): ElementFingerprint {
  const root = parseFragmentLikeLxml(pageHtml);
  const [first] = allDescendantElements(root);
  return elementToDict(first ?? root);
}
