import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * The build bible governs every decision in this repo. It used to live one
 * directory up, in a DIFFERENT git repo — unreviewed, ungated, and with no
 * history tying a rule to the commits that acted on it. It was moved here on
 * 2026-08-25 so that changing a rule costs the same review as changing code.
 *
 * These tests exist so the move cannot silently revert. Before it, `CLAUDE.md`
 * in this repo was a single line (`@AGENTS.md`); restoring that state — by
 * accident or by a tool that rewrites agent files — would put the rules back
 * out of reach of the gauntlet without failing anything.
 */

const BIBLE = readFileSync(join(process.cwd(), "CLAUDE.md"), "utf8");

describe("the build bible is tracked in this repo", () => {
  it("holds the real content, not a pointer to somewhere else", () => {
    // A pointer file is short. The bible is not.
    expect(BIBLE.split("\n").length).toBeGreaterThan(300);
  });

  it("still carries the sections the rest of the process depends on", () => {
    // Each of these is referenced by name elsewhere — in the PR template, in
    // CI_STATUS.md, or in code comments. Losing one silently breaks a
    // reference that reads as though it still resolves.
    for (const heading of [
      "## PRIME DIRECTIVES",
      "## THE 5 FATES",
      "## THE SELF-DESCRIPTION RULE",
      "## CAPABILITY ONBOARDING PIPELINE",
      "## ABSORPTION SCORE",
      "## CI/CD — THE GAUNTLET",
    ]) {
      expect(BIBLE, `missing section: ${heading}`).toContain(heading);
    }
  });

  it("keeps importing AGENTS.md, which `next dev` owns and rewrites", () => {
    // AGENTS.md is regenerated by Next's tooling. The bible has to import it
    // rather than absorb it, or the next `next dev` run reintroduces a second
    // copy of those rules.
    expect(BIBLE.split("\n")[0].trim()).toBe("@AGENTS.md");
  });

  it("names all five fates, including FIXTURE", () => {
    // FIXTURE was added 2026-08-24 and is the one fate with no Absorption
    // Score — a summary that drops it reads as though four fates exist.
    for (const fate of ["PORT", "SERVICE", "HARVEST", "FIXTURE", "CUT"]) {
      expect(BIBLE).toContain(`**${fate}**`);
    }
  });
});
