/**
 * Fidelity gate (gate 11) for the Scrapling port. Every score here is
 * compared against `kernel/fixtures/scrapling-golden.json`, which was
 * generated by CALLING THE REAL UPSTREAM SCRAPLING LIBRARY (0.4.9) — see
 * kernel/fixtures/generate_golden.py. This test does not check the port
 * against itself; it checks the port against the thing it is a port of.
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import {
  elementToDict,
  calculateSimilarityScore,
  relocate,
  parseFragmentLikeLxml,
  allDescendantElements,
  type ElementFingerprint,
} from "../../kernel/scrapling";

interface GoldenCase {
  name: string;
  originalHtml: string;
  candidateHtml: string;
  originalIndex: number;
  candidateIndex: number;
  originalFingerprint: {
    tag: string;
    attributes: Record<string, string>;
    text: string | null;
    path: string[];
    parent_name?: string;
    parent_attribs?: Record<string, string>;
    parent_text?: string | null;
    siblings?: string[];
    children?: string[];
  };
  expectedScore: number;
}

const fixturePath = join(__dirname, "..", "..", "kernel", "fixtures", "scrapling-golden.json");
const golden: { scraplingVersion: string; cases: GoldenCase[] } = JSON.parse(
  readFileSync(fixturePath, "utf8"),
);

/**
 * Mirrors the golden fixture's xpath `.//*[not(html|body|head)]`, run through
 * the SAME lxml-fragment-wrapping the port itself uses for real work
 * (`parseFragmentLikeLxml`) rather than a second, parallel parse path that
 * could silently drift from what the production code actually does.
 */
function selectableElements(html: string) {
  const root = parseFragmentLikeLxml(html);
  return allDescendantElements(root).filter((el) => !["body", "head"].includes(el.name));
}

describe(`Scrapling port fidelity vs upstream ${golden.scraplingVersion}`, () => {
  for (const testCase of golden.cases) {
    it(`${testCase.name} — score matches upstream exactly`, () => {
      const originalEl = selectableElements(testCase.originalHtml)[testCase.originalIndex];
      const candidateEl = selectableElements(testCase.candidateHtml)[testCase.candidateIndex];
      expect(originalEl, "fixture's original element not found by this port's parser").toBeDefined();
      expect(candidateEl, "fixture's candidate element not found by this port's parser").toBeDefined();

      const fingerprint = elementToDict(originalEl);
      const score = calculateSimilarityScore(fingerprint, candidateEl);

      expect(score).toBe(testCase.expectedScore);
    });

    it(`${testCase.name} — fingerprint shape matches upstream's element_to_dict`, () => {
      const originalEl = selectableElements(testCase.originalHtml)[testCase.originalIndex];
      const fp = elementToDict(originalEl);
      const g = testCase.originalFingerprint;

      expect(fp.tag).toBe(g.tag);
      expect(fp.attributes).toEqual(g.attributes);
      expect(fp.text).toBe(g.text);
      expect(fp.path).toEqual(g.path);
      expect(fp.parentName).toBe(g.parent_name);
      expect(fp.parentAttribs).toEqual(g.parent_attribs);
      expect(fp.parentText ?? null).toBe(g.parent_text ?? null);
      expect(fp.siblings).toEqual(g.siblings);
      expect(fp.children).toEqual(g.children);
    });
  }

  it("covers every case in the golden fixture — a shrinking fixture must not silently reduce coverage", () => {
    expect(golden.cases.length).toBeGreaterThanOrEqual(6);
  });
});

describe("relocate — the actual 'survives a redesign' capability", () => {
  it("finds the same logical element after tag, class and structure all change", () => {
    const original = selectableElements(
      '<html><body><div id="product"><span class="old-price-tag" id="pr-9981">$899</span></div></body></html>',
    )[1]; // the <span>
    const fingerprint = elementToDict(original);

    const redesignedPage =
      '<html><body><section id="product-v2"><p class="new-price-label" id="pr-9981">$899</p></section>' +
      '<footer><p class="copyright">nothing to do with the price</p></footer></body></html>';

    const result = relocate(fingerprint, redesignedPage);

    expect(result, "must find a match above the default 40% threshold").toBeDefined();
    expect(result!.matches).toHaveLength(1);
    expect(result!.matches[0].name).toBe("p");
    expect(result!.matches[0].attribs.id).toBe("pr-9981");
    // And it must NOT have matched the unrelated footer paragraph.
    expect(result!.matches.some((el) => el.attribs.class === "copyright")).toBe(false);
  });

  it("returns undefined when nothing on the page clears the threshold", () => {
    const fingerprint: ElementFingerprint = {
      tag: "div",
      attributes: { id: "very-specific-marker-xyz", class: "unique-marker" },
      text: "A very specific sentence that appears nowhere else at all.",
      path: ["html", "body", "div"],
    };

    const unrelatedPage = "<html><body><nav><a href='/x'>Link</a></nav></body></html>";
    expect(relocate(fingerprint, unrelatedPage, 40)).toBeUndefined();
  });

  it("returns every element tied at the highest score, not just the first", () => {
    // Two structurally identical siblings — a real page (e.g. a repeated
    // product card) can legitimately tie. `relocate` must not silently pick
    // one; the caller decides what to do with an ambiguous result.
    const fingerprint: ElementFingerprint = {
      tag: "li",
      attributes: { class: "card" },
      text: "X",
      path: ["html", "body", "ul", "li"],
    };

    const page =
      '<html><body><ul><li class="card">X</li><li class="card">X</li></ul></body></html>';
    const result = relocate(fingerprint, page, 40);

    expect(result!.matches).toHaveLength(2);
    expect(result!.score).toBe(100);
  });
});
